using System.Text;

namespace SecOps.Workbench.Core;

/// <summary>
/// Renders an analyst-facing Markdown case note from a triage result. The note is built from
/// synthetic data only and always frames response steps as dry-run recommendations.
/// </summary>
public static class CaseNote
{
    public static string Render(TriageResult result)
    {
        ArgumentNullException.ThrowIfNull(result);

        var alert = result.Alert;
        var builder = new StringBuilder();

        builder.AppendLine($"# Case Note: {alert.Title}");
        builder.AppendLine();
        builder.AppendLine($"_Synthetic case note generated by the SecOps Automation Workbench for alert `{alert.Id}`._");
        builder.AppendLine();

        builder.AppendLine("## Summary");
        builder.AppendLine();
        builder.AppendLine(
            $"A {alert.Severity} {alert.Category} alert from `{alert.Source}` involving principal " +
            $"`{alert.Principal}` on asset `{alert.Asset}`. Identity risk tier is " +
            $"{result.Enrichment.Identity.RiskTier} and asset criticality is " +
            $"{result.Enrichment.Asset.Criticality}. Recommended playbook: `{result.RecommendedPlaybook}`.");
        builder.AppendLine();

        builder.AppendLine("## Observables");
        builder.AppendLine();
        foreach (var observable in result.Enrichment.Observables)
        {
            builder.AppendLine($"- `{observable.Observable}` — {observable.Verdict}: {observable.Context}");
        }
        builder.AppendLine();

        builder.AppendLine("## Mapped techniques");
        builder.AppendLine();
        if (result.TechniqueIds.Count == 0)
        {
            builder.AppendLine("- None mapped.");
        }
        else
        {
            foreach (var technique in result.TechniqueIds)
            {
                builder.AppendLine($"- {technique} — {AttackTechniqueCatalog.NameFor(technique)}");
            }
        }
        builder.AppendLine();

        builder.AppendLine("## Recommended playbook");
        builder.AppendLine();
        builder.AppendLine($"`{result.RecommendedPlaybook}`");
        builder.AppendLine();

        builder.AppendLine("## Analyst checklist");
        builder.AppendLine();
        builder.AppendLine("- [ ] Confirm this is not known maintenance or an approved test.");
        builder.AppendLine("- [ ] Validate the principal and asset against your source of truth.");
        builder.AppendLine("- [ ] Confirm the mapped techniques fit the available evidence.");
        builder.AppendLine("- [ ] Decide whether to escalate, monitor, or close.");
        builder.AppendLine("- [ ] Record the decision and rationale in your case-management system.");
        builder.AppendLine();

        builder.AppendLine("## Dry-run response plan");
        builder.AppendLine();
        builder.AppendLine("All steps below are recommendations only. Nothing is executed automatically.");
        builder.AppendLine();
        var step = 1;
        foreach (var action in result.RecommendedActions)
        {
            builder.AppendLine($"{step}. (dry-run) {action}");
            step++;
        }
        builder.AppendLine();

        builder.AppendLine("## Limitations");
        builder.AppendLine();
        builder.AppendLine("- Generated from synthetic sample data by an engineering workbench, not a production SOC tool.");
        builder.AppendLine("- Enrichment is synthetic and deterministic; it is not sourced from real identity, asset, or threat-intel systems.");
        builder.AppendLine("- No response actions were taken; every step is a dry-run recommendation.");
        builder.AppendLine("- A human analyst must review and own any real-world decision.");

        return builder.ToString().TrimEnd();
    }
}
